### ISSUE TITLE
why do you stop ecs_agent ? 

### ISSUE THREAD

**Issue by fas3r** [calvinlfer/cassandra-ebs-cloudformation#1]
Hello, 

could you explain why you stop the ecs agent at the end ? By the way create example, thanks for sharing.

**Comment by calvinlfer** [comment]
Hey @fas3r glad you found it useful, I stop the ECS agent at the end because we don't use it (we don't use an ECS cluster). I could have picked a better AMI which only included Docker instead of Docker with the ECS agent.
